// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVjQF8-j-3y4TW-QO0K_3ToCzubGdcsMc',
    appId: '1:41322564927:web:c6556a34069137c91f978a',
    messagingSenderId: '41322564927',
    projectId: 'gemastik-bedaa',
    authDomain: 'gemastik-bedaa.firebaseapp.com',
    storageBucket: 'gemastik-bedaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX0Y0hk1k-5PoFHOIAwGygkaUbb3k8xZg',
    appId: '1:41322564927:android:3bba97b0c94c2e491f978a',
    messagingSenderId: '41322564927',
    projectId: 'gemastik-bedaa',
    storageBucket: 'gemastik-bedaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_jkOHK5Y16_SS8u06EzuCSXRCO1UGhY',
    appId: '1:41322564927:ios:e2ae58d1b6ddbc511f978a',
    messagingSenderId: '41322564927',
    projectId: 'gemastik-bedaa',
    storageBucket: 'gemastik-bedaa.appspot.com',
    iosBundleId: 'com.example.newbie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_jkOHK5Y16_SS8u06EzuCSXRCO1UGhY',
    appId: '1:41322564927:ios:3a7f25c170469c231f978a',
    messagingSenderId: '41322564927',
    projectId: 'gemastik-bedaa',
    storageBucket: 'gemastik-bedaa.appspot.com',
    iosBundleId: 'com.example.newbie.RunnerTests',
  );
}
